// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsnxwVALI5FBcblHdckp7mflh3vonMdgE',
    appId: '1:769428111995:web:6663fc96c798d6346b98de',
    messagingSenderId: '769428111995',
    projectId: 'tendertrust-trustforge',
    authDomain: 'tendertrust-trustforge.firebaseapp.com',
    storageBucket: 'tendertrust-trustforge.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNmpZIgZVAbss3ndPPXLOLu7ksi3jWpyw',
    appId: '1:769428111995:android:08287e728cca8f646b98de',
    messagingSenderId: '769428111995',
    projectId: 'tendertrust-trustforge',
    storageBucket: 'tendertrust-trustforge.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBIgU4c-CockkgGK2Au3M5a44YjmSLmjg',
    appId: '1:769428111995:ios:22cbfdbfad12c8586b98de',
    messagingSenderId: '769428111995',
    projectId: 'tendertrust-trustforge',
    storageBucket: 'tendertrust-trustforge.firebasestorage.app',
    iosBundleId: 'com.example.tenderTrust',
  );
}
